# The application's global config file. 

# Display Device
DISP_WIDTH_MM: 597
DISP_HEIGHT_MM: 335
DISP_WIDTH_PX: 3840
DISP_HEIGHT_PX: 2160

# Eyetracker Device
EYETRACKER_MOUNT_OFFSET_MM: 0.0  # Horiz offset (+/- from center)
EYETRACKER_SAMPLE_HZ: 90
EYETRACKER_BUFF_SZ: 4500
EYETRACKER_MARK_INTERVAL: 5
EYETRACKER_SMOOTH_OVER: 13
EYETRACKER_EXTERN_LIB_PATH: lib/so/eyetracker_gaze.so
EYETRACKER_PREP_SCRIPT_PATH: lib/sh/prep_eyetracker_gaze.sh
EYETRACKER_CALIB_PATH: /opt/app/data/eyetracker.calib
EYETRACKER_LICENSE_PATH: /opt/app/src/licenses/fast_aeye_typer_temp_se_license_key
EYETRACKER_WRITEBACK_SECONDS: 7
EYETRACKER_WRITEAFTER_SECONDS: 7

# On-screen Keyboard/HUD
HUD_DISP_TITLE: 'AEye TypeR'
HUD_DISP_WIDTH_PX: 1745
HUD_DISP_HEIGHT_PX: 253
HUD_STATUSPANEL_WIDTH_PX: 95
HUD_DISP_COORD_DIVISOR_X: 2     # Centered = 2
HUD_DISP_COORD_DIVISOR_Y: 1     # Bottom edge = 1
HUD_BTN_WIDTH: 3
HUD_KEYB_JSON: 'lib/json/keyboard_us.json'

# Event Logging
EVENTLOG_RAW_ROOTDIR: /opt/app/data/logs      # Raw log data directory

# Data processing
GAZE_TIME_CONVERT_IPLIER: .00001
MOUSE_TIME_CONVERT_IPLIER: 10

# ANSII color codes (note that '\e' is yaml equiv of '\033')
ANSII_ESC_BOLD: "\e[1m"
ANSII_ESC_OK: "\e[92m"
ANSII_ESC_WARNING: "\e[38;5;214m"
ANSII_ESC_ERROR: "\e[91m"
ANSII_ESC_ENDCOLOR: "\e[0m"

